import type { Template } from './types'

export const MOCK_TEMPLATES: Template[] = [
  {
    id: 'mock-001',
    occasion_slug: 'wedding',
    title: 'Royal Garden Wedding',
    style_tags: ['floral', 'elegant', 'romantic'],
    colour_palette: ['#E11D48', '#F9A8D4', '#FFF1F2', '#831843'],
    orientation: 'portrait',
    price_inr: 49,
    preview_url: null,
    hd_template_url: null,
    fabric_json: {
      version: '5.5.2',
      background: '#FFF1F2',
      objects: [
        {
          type: 'rect',
          version: '5.5.2',
          originX: 'left',
          originY: 'top',
          left: 0,
          top: 0,
          width: 800,
          height: 1000,
          fill: '#FFF1F2',
          stroke: '#F9A8D4',
          strokeWidth: 8,
          rx: 0,
          ry: 0,
          selectable: false,
        },
        {
          type: 'textbox',
          version: '5.5.2',
          originX: 'center',
          originY: 'top',
          left: 400,
          top: 120,
          width: 650,
          text: 'Arjun & Priya',
          fontSize: 56,
          fontFamily: 'Playfair Display',
          fontWeight: 'bold',
          fill: '#831843',
          textAlign: 'center',
        },
        {
          type: 'textbox',
          version: '5.5.2',
          originX: 'center',
          originY: 'top',
          left: 400,
          top: 220,
          width: 650,
          text: 'Together with their families\nrequest your presence at their wedding',
          fontSize: 22,
          fontFamily: 'Georgia',
          fill: '#BE185D',
          textAlign: 'center',
        },
        {
          type: 'textbox',
          version: '5.5.2',
          originX: 'center',
          originY: 'top',
          left: 400,
          top: 520,
          width: 600,
          text: '📅 Saturday, 15th February 2026\n📍 The Grand Palace Banquet Hall\nMumbai, Maharashtra',
          fontSize: 24,
          fontFamily: 'Georgia',
          fill: '#9D174D',
          textAlign: 'center',
        },
        {
          type: 'textbox',
          version: '5.5.2',
          originX: 'center',
          originY: 'top',
          left: 400,
          top: 860,
          width: 500,
          text: 'RSVP by 10th February\n+91 98765 43210',
          fontSize: 18,
          fontFamily: 'Georgia',
          fill: '#BE185D',
          textAlign: 'center',
        },
      ],
    },
    ai_prompt: 'Create a romantic floral wedding invitation with rose gold accents',
    is_active: true,
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'mock-002',
    occasion_slug: 'birthday-kids',
    title: 'Rainbow Unicorn Birthday',
    style_tags: ['colorful', 'playful', 'whimsical'],
    colour_palette: ['#F59E0B', '#FDE68A', '#FFFBEB', '#92400E'],
    orientation: 'portrait',
    price_inr: 0,
    preview_url: null,
    hd_template_url: null,
    fabric_json: {
      version: '5.5.2',
      background: '#FFFBEB',
      objects: [
        {
          type: 'rect',
          version: '5.5.2',
          originX: 'left',
          originY: 'top',
          left: 0,
          top: 0,
          width: 800,
          height: 1000,
          fill: '#FFFBEB',
          stroke: '#FDE68A',
          strokeWidth: 12,
          rx: 0,
          ry: 0,
          selectable: false,
        },
        {
          type: 'textbox',
          version: '5.5.2',
          originX: 'center',
          originY: 'top',
          left: 400,
          top: 80,
          width: 700,
          text: "You're Invited! 🎂",
          fontSize: 52,
          fontFamily: 'Arial Rounded MT Bold',
          fontWeight: 'bold',
          fill: '#92400E',
          textAlign: 'center',
        },
        {
          type: 'textbox',
          version: '5.5.2',
          originX: 'center',
          originY: 'top',
          left: 400,
          top: 200,
          width: 700,
          text: "Aanya's 5th Birthday Party! 🦄🌈",
          fontSize: 32,
          fontFamily: 'Arial',
          fontWeight: 'bold',
          fill: '#D97706',
          textAlign: 'center',
        },
        {
          type: 'textbox',
          version: '5.5.2',
          originX: 'center',
          originY: 'top',
          left: 400,
          top: 500,
          width: 650,
          text: '📅 Sunday, 22nd March 2026\n⏰ 11:00 AM – 3:00 PM\n📍 Sunshine Kids Club\nBangalore',
          fontSize: 26,
          fontFamily: 'Arial',
          fill: '#92400E',
          textAlign: 'center',
        },
        {
          type: 'textbox',
          version: '5.5.2',
          originX: 'center',
          originY: 'top',
          left: 400,
          top: 860,
          width: 600,
          text: 'RSVP: Mummy (Priti) — 98000 12345\nDress Code: Bright & Colorful!',
          fontSize: 20,
          fontFamily: 'Arial',
          fill: '#B45309',
          textAlign: 'center',
        },
      ],
    },
    ai_prompt: 'Bright colorful kids birthday invitation with unicorns and rainbows',
    is_active: true,
    created_at: '2026-01-02T00:00:00Z',
  },
  {
    id: 'mock-003',
    occasion_slug: 'diwali',
    title: 'Golden Diwali Celebration',
    style_tags: ['festive', 'traditional', 'gold'],
    colour_palette: ['#F59E0B', '#92400E', '#1C0A00', '#FDE68A'],
    orientation: 'landscape',
    price_inr: 29,
    preview_url: null,
    hd_template_url: null,
    fabric_json: {
      version: '5.5.2',
      background: '#1C0A00',
      objects: [
        {
          type: 'rect',
          version: '5.5.2',
          originX: 'left',
          originY: 'top',
          left: 0,
          top: 0,
          width: 1200,
          height: 800,
          fill: '#1C0A00',
          stroke: '#F59E0B',
          strokeWidth: 10,
          rx: 0,
          ry: 0,
          selectable: false,
        },
        {
          type: 'textbox',
          version: '5.5.2',
          originX: 'center',
          originY: 'top',
          left: 600,
          top: 80,
          width: 1000,
          text: '🪔 Shubh Deepavali 🪔',
          fontSize: 60,
          fontFamily: 'Georgia',
          fontWeight: 'bold',
          fill: '#F59E0B',
          textAlign: 'center',
        },
        {
          type: 'textbox',
          version: '5.5.2',
          originX: 'center',
          originY: 'top',
          left: 600,
          top: 200,
          width: 900,
          text: 'The Sharma Family\ncordially invites you to celebrate the Festival of Lights',
          fontSize: 28,
          fontFamily: 'Georgia',
          fill: '#FDE68A',
          textAlign: 'center',
        },
        {
          type: 'textbox',
          version: '5.5.2',
          originX: 'center',
          originY: 'top',
          left: 600,
          top: 450,
          width: 800,
          text: '📅 Friday, 20th October 2026\n⏰ 6:00 PM onwards\n📍 12, Laxmi Nagar, New Delhi',
          fontSize: 26,
          fontFamily: 'Georgia',
          fill: '#FCD34D',
          textAlign: 'center',
        },
        {
          type: 'textbox',
          version: '5.5.2',
          originX: 'center',
          originY: 'top',
          left: 600,
          top: 700,
          width: 700,
          text: 'Sweets | Crackers | Puja | Dinner\nRSVP: +91 99887 76655',
          fontSize: 20,
          fontFamily: 'Georgia',
          fill: '#F59E0B',
          textAlign: 'center',
        },
      ],
    },
    ai_prompt: 'Traditional Diwali invitation with diyas and golden theme on dark background',
    is_active: true,
    created_at: '2026-01-03T00:00:00Z',
  },
  {
    id: 'mock-004',
    occasion_slug: 'engagement',
    title: 'Pink Blossom Engagement',
    style_tags: ['floral', 'romantic', 'modern'],
    colour_palette: ['#EC4899', '#FBCFE8', '#FDF2F8', '#9D174D'],
    orientation: 'portrait',
    price_inr: 49,
    preview_url: null,
    hd_template_url: null,
    fabric_json: {
      version: '5.5.2',
      background: '#FDF2F8',
      objects: [
        {
          type: 'rect',
          version: '5.5.2',
          originX: 'left',
          originY: 'top',
          left: 0,
          top: 0,
          width: 800,
          height: 1000,
          fill: '#FDF2F8',
          stroke: '#FBCFE8',
          strokeWidth: 6,
          rx: 0,
          ry: 0,
          selectable: false,
        },
        {
          type: 'textbox',
          version: '5.5.2',
          originX: 'center',
          originY: 'top',
          left: 400,
          top: 100,
          width: 680,
          text: '💑 We Said Yes! 💍',
          fontSize: 48,
          fontFamily: 'Playfair Display',
          fontWeight: 'bold',
          fill: '#9D174D',
          textAlign: 'center',
        },
        {
          type: 'textbox',
          version: '5.5.2',
          originX: 'center',
          originY: 'top',
          left: 400,
          top: 220,
          width: 680,
          text: 'Rahul & Sneha\nare getting Engaged!',
          fontSize: 36,
          fontFamily: 'Playfair Display',
          fill: '#BE185D',
          textAlign: 'center',
        },
        {
          type: 'textbox',
          version: '5.5.2',
          originX: 'center',
          originY: 'top',
          left: 400,
          top: 520,
          width: 620,
          text: '📅 Sunday, 8th March 2026\n⏰ 5:00 PM\n📍 Taj Hotel Banquet\nPune, Maharashtra',
          fontSize: 24,
          fontFamily: 'Georgia',
          fill: '#9D174D',
          textAlign: 'center',
        },
        {
          type: 'textbox',
          version: '5.5.2',
          originX: 'center',
          originY: 'top',
          left: 400,
          top: 850,
          width: 580,
          text: 'Join us for the ring ceremony & celebration!\nRSVP: 97654 32109',
          fontSize: 18,
          fontFamily: 'Georgia',
          fill: '#BE185D',
          textAlign: 'center',
        },
      ],
    },
    ai_prompt: 'Elegant pink blossom engagement announcement invitation',
    is_active: true,
    created_at: '2026-01-04T00:00:00Z',
  },
  {
    id: 'mock-005',
    occasion_slug: 'graduation',
    title: 'Academic Excellence Graduation',
    style_tags: ['modern', 'minimal', 'elegant'],
    colour_palette: ['#1D4ED8', '#DBEAFE', '#EFF6FF', '#1E3A8A'],
    orientation: 'landscape',
    price_inr: 29,
    preview_url: null,
    hd_template_url: null,
    fabric_json: {
      version: '5.5.2',
      background: '#EFF6FF',
      objects: [
        {
          type: 'rect',
          version: '5.5.2',
          originX: 'left',
          originY: 'top',
          left: 0,
          top: 0,
          width: 1200,
          height: 800,
          fill: '#EFF6FF',
          stroke: '#1D4ED8',
          strokeWidth: 8,
          rx: 0,
          ry: 0,
          selectable: false,
        },
        {
          type: 'textbox',
          version: '5.5.2',
          originX: 'center',
          originY: 'top',
          left: 600,
          top: 80,
          width: 1000,
          text: '🎓 Graduation Celebration 🎓',
          fontSize: 54,
          fontFamily: 'Playfair Display',
          fontWeight: 'bold',
          fill: '#1E3A8A',
          textAlign: 'center',
        },
        {
          type: 'textbox',
          version: '5.5.2',
          originX: 'center',
          originY: 'top',
          left: 600,
          top: 200,
          width: 900,
          text: 'Please join us to celebrate\nRohan Mehta\'s graduation from IIT Bombay',
          fontSize: 28,
          fontFamily: 'Georgia',
          fill: '#1D4ED8',
          textAlign: 'center',
        },
        {
          type: 'textbox',
          version: '5.5.2',
          originX: 'center',
          originY: 'top',
          left: 600,
          top: 440,
          width: 800,
          text: '📅 Saturday, 18th April 2026\n⏰ 7:00 PM onwards\n📍 Mehta Residence, Juhu, Mumbai',
          fontSize: 26,
          fontFamily: 'Georgia',
          fill: '#1E3A8A',
          textAlign: 'center',
        },
        {
          type: 'textbox',
          version: '5.5.2',
          originX: 'center',
          originY: 'top',
          left: 600,
          top: 700,
          width: 700,
          text: 'Dinner & Celebration | Dress: Smart Casual\nRSVP: +91 88776 65544',
          fontSize: 20,
          fontFamily: 'Georgia',
          fill: '#2563EB',
          textAlign: 'center',
        },
      ],
    },
    ai_prompt: 'Professional graduation party invitation with navy blue academic theme',
    is_active: true,
    created_at: '2026-01-05T00:00:00Z',
  },
  {
    id: 'mock-006',
    occasion_slug: 'baby-shower',
    title: 'Sweet Baby Blue Shower',
    style_tags: ['cute', 'pastel', 'minimal'],
    colour_palette: ['#06B6D4', '#CFFAFE', '#ECFEFF', '#0E7490'],
    orientation: 'portrait',
    price_inr: 0,
    preview_url: null,
    hd_template_url: null,
    fabric_json: {
      version: '5.5.2',
      background: '#ECFEFF',
      objects: [
        {
          type: 'rect',
          version: '5.5.2',
          originX: 'left',
          originY: 'top',
          left: 0,
          top: 0,
          width: 800,
          height: 1000,
          fill: '#ECFEFF',
          stroke: '#CFFAFE',
          strokeWidth: 8,
          rx: 0,
          ry: 0,
          selectable: false,
        },
        {
          type: 'textbox',
          version: '5.5.2',
          originX: 'center',
          originY: 'top',
          left: 400,
          top: 100,
          width: 700,
          text: '👶 Baby Shower 🌟',
          fontSize: 50,
          fontFamily: 'Arial Rounded MT Bold',
          fontWeight: 'bold',
          fill: '#0E7490',
          textAlign: 'center',
        },
        {
          type: 'textbox',
          version: '5.5.2',
          originX: 'center',
          originY: 'top',
          left: 400,
          top: 220,
          width: 680,
          text: 'Celebrating the arrival of\nDivya & Kiran\'s Baby Boy!',
          fontSize: 30,
          fontFamily: 'Georgia',
          fill: '#0891B2',
          textAlign: 'center',
        },
        {
          type: 'textbox',
          version: '5.5.2',
          originX: 'center',
          originY: 'top',
          left: 400,
          top: 520,
          width: 640,
          text: '📅 Sunday, 5th April 2026\n⏰ 3:00 PM – 7:00 PM\n📍 Bliss Banquet Hall\nHyderabad',
          fontSize: 24,
          fontFamily: 'Georgia',
          fill: '#0E7490',
          textAlign: 'center',
        },
        {
          type: 'textbox',
          version: '5.5.2',
          originX: 'center',
          originY: 'top',
          left: 400,
          top: 860,
          width: 580,
          text: 'Games • Gifts • Celebration\nRSVP: Divya — 95555 44433',
          fontSize: 20,
          fontFamily: 'Georgia',
          fill: '#0891B2',
          textAlign: 'center',
        },
      ],
    },
    ai_prompt: 'Cute baby shower invitation with soft blue and white pastel colors',
    is_active: true,
    created_at: '2026-01-06T00:00:00Z',
  },
  {
    id: 'mock-007',
    occasion_slug: 'housewarming',
    title: 'Griha Pravesh Ceremony',
    style_tags: ['traditional', 'festive', 'warm'],
    colour_palette: ['#059669', '#A7F3D0', '#ECFDF5', '#065F46'],
    orientation: 'portrait',
    price_inr: 29,
    preview_url: null,
    hd_template_url: null,
    fabric_json: {
      version: '5.5.2',
      background: '#ECFDF5',
      objects: [
        {
          type: 'rect',
          version: '5.5.2',
          originX: 'left',
          originY: 'top',
          left: 0,
          top: 0,
          width: 800,
          height: 1000,
          fill: '#ECFDF5',
          stroke: '#6EE7B7',
          strokeWidth: 8,
          rx: 0,
          ry: 0,
          selectable: false,
        },
        {
          type: 'textbox',
          version: '5.5.2',
          originX: 'center',
          originY: 'top',
          left: 400,
          top: 90,
          width: 700,
          text: '🏠 Griha Pravesh 🪷',
          fontSize: 50,
          fontFamily: 'Playfair Display',
          fontWeight: 'bold',
          fill: '#065F46',
          textAlign: 'center',
        },
        {
          type: 'textbox',
          version: '5.5.2',
          originX: 'center',
          originY: 'top',
          left: 400,
          top: 210,
          width: 680,
          text: 'With great joy and gratitude,\nthe Patel Family invites you\nto bless our new home',
          fontSize: 26,
          fontFamily: 'Georgia',
          fill: '#047857',
          textAlign: 'center',
        },
        {
          type: 'textbox',
          version: '5.5.2',
          originX: 'center',
          originY: 'top',
          left: 400,
          top: 530,
          width: 640,
          text: '📅 Thursday, 9th April 2026\n⏰ Morning Puja: 8:00 AM\n🍽️ Lunch at 12:00 PM\n📍 Plot 45, Sector 9, Gurugram',
          fontSize: 24,
          fontFamily: 'Georgia',
          fill: '#065F46',
          textAlign: 'center',
        },
        {
          type: 'textbox',
          version: '5.5.2',
          originX: 'center',
          originY: 'top',
          left: 400,
          top: 870,
          width: 580,
          text: 'Your presence and blessings\nare our greatest gift.\nRSVP: 90000 11122',
          fontSize: 18,
          fontFamily: 'Georgia',
          fill: '#047857',
          textAlign: 'center',
        },
      ],
    },
    ai_prompt: 'Traditional housewarming griha pravesh invitation with green and floral accents',
    is_active: true,
    created_at: '2026-01-07T00:00:00Z',
  },
  {
    id: 'mock-008',
    occasion_slug: 'birthday-adult',
    title: 'Midnight Blue Birthday Gala',
    style_tags: ['elegant', 'modern', 'bold'],
    colour_palette: ['#4F46E5', '#C7D2FE', '#EEF2FF', '#312E81'],
    orientation: 'portrait',
    price_inr: 29,
    preview_url: null,
    hd_template_url: null,
    fabric_json: {
      version: '5.5.2',
      background: '#1E1B4B',
      objects: [
        {
          type: 'rect',
          version: '5.5.2',
          originX: 'left',
          originY: 'top',
          left: 0,
          top: 0,
          width: 800,
          height: 1000,
          fill: '#1E1B4B',
          stroke: '#818CF8',
          strokeWidth: 6,
          rx: 0,
          ry: 0,
          selectable: false,
        },
        {
          type: 'textbox',
          version: '5.5.2',
          originX: 'center',
          originY: 'top',
          left: 400,
          top: 100,
          width: 700,
          text: '🎉 You Are Invited',
          fontSize: 48,
          fontFamily: 'Playfair Display',
          fontWeight: 'bold',
          fill: '#C7D2FE',
          textAlign: 'center',
        },
        {
          type: 'textbox',
          version: '5.5.2',
          originX: 'center',
          originY: 'top',
          left: 400,
          top: 220,
          width: 680,
          text: "Vikram's 30th Birthday Bash!\nCelebrate three decades of awesomeness",
          fontSize: 28,
          fontFamily: 'Georgia',
          fill: '#A5B4FC',
          textAlign: 'center',
        },
        {
          type: 'textbox',
          version: '5.5.2',
          originX: 'center',
          originY: 'top',
          left: 400,
          top: 520,
          width: 640,
          text: '📅 Saturday, 14th February 2026\n⏰ 8:00 PM – Midnight\n📍 Skyline Rooftop Lounge\nBandra, Mumbai',
          fontSize: 24,
          fontFamily: 'Georgia',
          fill: '#C7D2FE',
          textAlign: 'center',
        },
        {
          type: 'textbox',
          version: '5.5.2',
          originX: 'center',
          originY: 'top',
          left: 400,
          top: 870,
          width: 580,
          text: 'Cocktails | Music | Dancing\nDress: Black Tie Optional\nRSVP: 98765 43210',
          fontSize: 20,
          fontFamily: 'Georgia',
          fill: '#818CF8',
          textAlign: 'center',
        },
      ],
    },
    ai_prompt: 'Sophisticated adult birthday party invitation with dark indigo and gold accents',
    is_active: true,
    created_at: '2026-01-08T00:00:00Z',
  },
  {
    id: 'mock-009',
    occasion_slug: 'office-party',
    title: 'Annual Corporate Gala',
    style_tags: ['professional', 'modern', 'minimal'],
    colour_palette: ['#1D4ED8', '#DBEAFE', '#F8FAFC', '#1E3A8A'],
    orientation: 'landscape',
    price_inr: 49,
    preview_url: null,
    hd_template_url: null,
    fabric_json: {
      version: '5.5.2',
      background: '#F8FAFC',
      objects: [
        {
          type: 'rect',
          version: '5.5.2',
          originX: 'left',
          originY: 'top',
          left: 0,
          top: 0,
          width: 1200,
          height: 800,
          fill: '#F8FAFC',
          stroke: '#1D4ED8',
          strokeWidth: 10,
          rx: 0,
          ry: 0,
          selectable: false,
        },
        {
          type: 'textbox',
          version: '5.5.2',
          originX: 'center',
          originY: 'top',
          left: 600,
          top: 80,
          width: 1000,
          text: '🏢 Annual Office Party 2026',
          fontSize: 52,
          fontFamily: 'Playfair Display',
          fontWeight: 'bold',
          fill: '#1E3A8A',
          textAlign: 'center',
        },
        {
          type: 'textbox',
          version: '5.5.2',
          originX: 'center',
          originY: 'top',
          left: 600,
          top: 200,
          width: 900,
          text: 'TechCorp India Pvt. Ltd.\ninvites all team members and their families',
          fontSize: 28,
          fontFamily: 'Georgia',
          fill: '#1D4ED8',
          textAlign: 'center',
        },
        {
          type: 'textbox',
          version: '5.5.2',
          originX: 'center',
          originY: 'top',
          left: 600,
          top: 440,
          width: 800,
          text: '📅 Friday, 19th December 2025\n⏰ 6:30 PM\n📍 Leela Hotel Grand Ballroom, Bengaluru',
          fontSize: 26,
          fontFamily: 'Georgia',
          fill: '#1E3A8A',
          textAlign: 'center',
        },
        {
          type: 'textbox',
          version: '5.5.2',
          originX: 'center',
          originY: 'top',
          left: 600,
          top: 700,
          width: 700,
          text: 'Awards | Dinner | Entertainment\nPlease RSVP to hr@techcorp.in by Dec 15',
          fontSize: 20,
          fontFamily: 'Georgia',
          fill: '#2563EB',
          textAlign: 'center',
        },
      ],
    },
    ai_prompt: 'Professional corporate annual party invitation with blue and white color scheme',
    is_active: true,
    created_at: '2026-01-09T00:00:00Z',
  },
  {
    id: 'mock-010',
    occasion_slug: 'mehendi',
    title: 'Verdant Mehendi Night',
    style_tags: ['traditional', 'floral', 'festive'],
    colour_palette: ['#059669', '#6EE7B7', '#D1FAE5', '#064E3B'],
    orientation: 'portrait',
    price_inr: 0,
    preview_url: null,
    hd_template_url: null,
    fabric_json: {
      version: '5.5.2',
      background: '#F0FDF4',
      objects: [
        {
          type: 'rect',
          version: '5.5.2',
          originX: 'left',
          originY: 'top',
          left: 0,
          top: 0,
          width: 800,
          height: 1000,
          fill: '#F0FDF4',
          stroke: '#6EE7B7',
          strokeWidth: 6,
          rx: 0,
          ry: 0,
          selectable: false,
        },
        {
          type: 'textbox',
          version: '5.5.2',
          originX: 'center',
          originY: 'top',
          left: 400,
          top: 90,
          width: 700,
          text: '🌿 Mehendi Ceremony 🌿',
          fontSize: 46,
          fontFamily: 'Playfair Display',
          fontWeight: 'bold',
          fill: '#064E3B',
          textAlign: 'center',
        },
        {
          type: 'textbox',
          version: '5.5.2',
          originX: 'center',
          originY: 'top',
          left: 400,
          top: 210,
          width: 680,
          text: 'Join us for the beautiful Mehendi ceremony\nof dear Anjali on the eve of her wedding',
          fontSize: 24,
          fontFamily: 'Georgia',
          fill: '#047857',
          textAlign: 'center',
        },
        {
          type: 'textbox',
          version: '5.5.2',
          originX: 'center',
          originY: 'top',
          left: 400,
          top: 520,
          width: 640,
          text: '📅 Thursday, 12th February 2026\n⏰ 4:00 PM onwards\n📍 Verma Residence\nJaipur, Rajasthan',
          fontSize: 24,
          fontFamily: 'Georgia',
          fill: '#064E3B',
          textAlign: 'center',
        },
        {
          type: 'textbox',
          version: '5.5.2',
          originX: 'center',
          originY: 'top',
          left: 400,
          top: 870,
          width: 580,
          text: 'Mehndi | Music | Dance | Snacks\nLadies Only Event 🌸\nRSVP: 98100 23456',
          fontSize: 18,
          fontFamily: 'Georgia',
          fill: '#047857',
          textAlign: 'center',
        },
      ],
    },
    ai_prompt: 'Traditional mehendi ceremony invitation with green floral patterns',
    is_active: true,
    created_at: '2026-01-10T00:00:00Z',
  },
  {
    id: 'mock-011',
    occasion_slug: 'christmas',
    title: 'Festive Christmas Party',
    style_tags: ['festive', 'colorful', 'bold'],
    colour_palette: ['#DC2626', '#16A34A', '#FFFBEB', '#991B1B'],
    orientation: 'landscape',
    price_inr: 29,
    preview_url: null,
    hd_template_url: null,
    fabric_json: {
      version: '5.5.2',
      background: '#FFFBEB',
      objects: [
        {
          type: 'rect',
          version: '5.5.2',
          originX: 'left',
          originY: 'top',
          left: 0,
          top: 0,
          width: 1200,
          height: 800,
          fill: '#FFFBEB',
          stroke: '#DC2626',
          strokeWidth: 10,
          rx: 0,
          ry: 0,
          selectable: false,
        },
        {
          type: 'textbox',
          version: '5.5.2',
          originX: 'center',
          originY: 'top',
          left: 600,
          top: 80,
          width: 1000,
          text: '🎄 Christmas Party 2025 🎅',
          fontSize: 56,
          fontFamily: 'Playfair Display',
          fontWeight: 'bold',
          fill: '#991B1B',
          textAlign: 'center',
        },
        {
          type: 'textbox',
          version: '5.5.2',
          originX: 'center',
          originY: 'top',
          left: 600,
          top: 200,
          width: 900,
          text: 'The D\'Souza Family\nwishes you a Merry Christmas!\nJoin us for an evening of joy and celebration',
          fontSize: 26,
          fontFamily: 'Georgia',
          fill: '#16A34A',
          textAlign: 'center',
        },
        {
          type: 'textbox',
          version: '5.5.2',
          originX: 'center',
          originY: 'top',
          left: 600,
          top: 480,
          width: 800,
          text: '📅 Thursday, 25th December 2025\n⏰ 6:00 PM\n📍 D\'Souza Residence, Bandra West, Mumbai',
          fontSize: 26,
          fontFamily: 'Georgia',
          fill: '#991B1B',
          textAlign: 'center',
        },
        {
          type: 'textbox',
          version: '5.5.2',
          originX: 'center',
          originY: 'top',
          left: 600,
          top: 700,
          width: 700,
          text: 'Carols | Gifts | Christmas Dinner\nRSVP: Maria — 91234 56789',
          fontSize: 20,
          fontFamily: 'Georgia',
          fill: '#16A34A',
          textAlign: 'center',
        },
      ],
    },
    ai_prompt: 'Festive Christmas party invitation with red and green holiday colors',
    is_active: true,
    created_at: '2026-01-11T00:00:00Z',
  },
  {
    id: 'mock-012',
    occasion_slug: 'anniversary',
    title: 'Silver Wedding Anniversary',
    style_tags: ['elegant', 'romantic', 'classic'],
    colour_palette: ['#E11D48', '#FECDD3', '#FFF1F2', '#9F1239'],
    orientation: 'portrait',
    price_inr: 99,
    preview_url: null,
    hd_template_url: null,
    fabric_json: {
      version: '5.5.2',
      background: '#FFF1F2',
      objects: [
        {
          type: 'rect',
          version: '5.5.2',
          originX: 'left',
          originY: 'top',
          left: 0,
          top: 0,
          width: 800,
          height: 1000,
          fill: '#FFF1F2',
          stroke: '#FECDD3',
          strokeWidth: 8,
          rx: 0,
          ry: 0,
          selectable: false,
        },
        {
          type: 'textbox',
          version: '5.5.2',
          originX: 'center',
          originY: 'top',
          left: 400,
          top: 90,
          width: 700,
          text: '💝 25 Years of Love 💝',
          fontSize: 48,
          fontFamily: 'Playfair Display',
          fontWeight: 'bold',
          fill: '#9F1239',
          textAlign: 'center',
        },
        {
          type: 'textbox',
          version: '5.5.2',
          originX: 'center',
          originY: 'top',
          left: 400,
          top: 210,
          width: 680,
          text: 'Mr. & Mrs. Suresh Kumar\ncelebrate 25 years of togetherness\nSilver Jubilee Anniversary',
          fontSize: 26,
          fontFamily: 'Georgia',
          fill: '#BE123C',
          textAlign: 'center',
        },
        {
          type: 'textbox',
          version: '5.5.2',
          originX: 'center',
          originY: 'top',
          left: 400,
          top: 540,
          width: 640,
          text: '📅 Saturday, 28th February 2026\n⏰ 7:00 PM\n📍 The Oberoi Ballroom\nChennai, Tamil Nadu',
          fontSize: 24,
          fontFamily: 'Georgia',
          fill: '#9F1239',
          textAlign: 'center',
        },
        {
          type: 'textbox',
          version: '5.5.2',
          originX: 'center',
          originY: 'top',
          left: 400,
          top: 870,
          width: 580,
          text: 'Renewing vows & celebrating with loved ones\nDress: Formal\nRSVP: 98400 55566',
          fontSize: 18,
          fontFamily: 'Georgia',
          fill: '#BE123C',
          textAlign: 'center',
        },
      ],
    },
    ai_prompt: 'Elegant silver anniversary celebration invitation with rose and white tones',
    is_active: true,
    created_at: '2026-01-12T00:00:00Z',
  },
  {
    id: 'mock-013',
    occasion_slug: 'sangeet',
    title: 'Bollywood Sangeet Night',
    style_tags: ['vibrant', 'festive', 'bold'],
    colour_palette: ['#8B5CF6', '#DDD6FE', '#F5F3FF', '#4C1D95'],
    orientation: 'landscape',
    price_inr: 29,
    preview_url: null,
    hd_template_url: null,
    fabric_json: {
      version: '5.5.2',
      background: '#2E1065',
      objects: [
        {
          type: 'rect',
          version: '5.5.2',
          originX: 'left',
          originY: 'top',
          left: 0,
          top: 0,
          width: 1200,
          height: 800,
          fill: '#2E1065',
          stroke: '#A78BFA',
          strokeWidth: 8,
          rx: 0,
          ry: 0,
          selectable: false,
        },
        {
          type: 'textbox',
          version: '5.5.2',
          originX: 'center',
          originY: 'top',
          left: 600,
          top: 80,
          width: 1000,
          text: '🎵 Sangeet Night 🎶',
          fontSize: 60,
          fontFamily: 'Playfair Display',
          fontWeight: 'bold',
          fill: '#C4B5FD',
          textAlign: 'center',
        },
        {
          type: 'textbox',
          version: '5.5.2',
          originX: 'center',
          originY: 'top',
          left: 600,
          top: 200,
          width: 900,
          text: 'Dance, sing and celebrate with us!\nOn the eve of Neha & Dev\'s wedding',
          fontSize: 28,
          fontFamily: 'Georgia',
          fill: '#A78BFA',
          textAlign: 'center',
        },
        {
          type: 'textbox',
          version: '5.5.2',
          originX: 'center',
          originY: 'top',
          left: 600,
          top: 450,
          width: 800,
          text: '📅 Friday, 13th February 2026\n⏰ 7:00 PM – 11:00 PM\n📍 Crystal Palace Banquets, Ludhiana',
          fontSize: 26,
          fontFamily: 'Georgia',
          fill: '#DDD6FE',
          textAlign: 'center',
        },
        {
          type: 'textbox',
          version: '5.5.2',
          originX: 'center',
          originY: 'top',
          left: 600,
          top: 700,
          width: 700,
          text: 'Live Music | Group Dance | Dinner\nDress: Ethnic Chic\nRSVP: 97700 88899',
          fontSize: 20,
          fontFamily: 'Georgia',
          fill: '#8B5CF6',
          textAlign: 'center',
        },
      ],
    },
    ai_prompt: 'Vibrant Sangeet night invitation with purple and gold Bollywood theme',
    is_active: true,
    created_at: '2026-01-13T00:00:00Z',
  },
  {
    id: 'mock-014',
    occasion_slug: 'new-year',
    title: 'New Year Eve Extravaganza',
    style_tags: ['bold', 'modern', 'festive'],
    colour_palette: ['#1D4ED8', '#FCD34D', '#111827', '#F59E0B'],
    orientation: 'landscape',
    price_inr: 49,
    preview_url: null,
    hd_template_url: null,
    fabric_json: {
      version: '5.5.2',
      background: '#111827',
      objects: [
        {
          type: 'rect',
          version: '5.5.2',
          originX: 'left',
          originY: 'top',
          left: 0,
          top: 0,
          width: 1200,
          height: 800,
          fill: '#111827',
          stroke: '#FCD34D',
          strokeWidth: 8,
          rx: 0,
          ry: 0,
          selectable: false,
        },
        {
          type: 'textbox',
          version: '5.5.2',
          originX: 'center',
          originY: 'top',
          left: 600,
          top: 80,
          width: 1000,
          text: '🎆 New Year 2027 🎆',
          fontSize: 64,
          fontFamily: 'Playfair Display',
          fontWeight: 'bold',
          fill: '#FCD34D',
          textAlign: 'center',
        },
        {
          type: 'textbox',
          version: '5.5.2',
          originX: 'center',
          originY: 'top',
          left: 600,
          top: 200,
          width: 900,
          text: 'Ring in the New Year with us!\nCountdown Party hosted by the Kapoor Family',
          fontSize: 28,
          fontFamily: 'Georgia',
          fill: '#93C5FD',
          textAlign: 'center',
        },
        {
          type: 'textbox',
          version: '5.5.2',
          originX: 'center',
          originY: 'top',
          left: 600,
          top: 450,
          width: 800,
          text: '📅 Wednesday, 31st December 2026\n⏰ 9:00 PM – 2:00 AM\n📍 Rooftop Garden, The Westin, Gurgaon',
          fontSize: 26,
          fontFamily: 'Georgia',
          fill: '#FCD34D',
          textAlign: 'center',
        },
        {
          type: 'textbox',
          version: '5.5.2',
          originX: 'center',
          originY: 'top',
          left: 600,
          top: 700,
          width: 700,
          text: 'Cocktails | DJ | Midnight Fireworks | Dinner\nDress: Glamorous\nRSVP: 99001 23344',
          fontSize: 20,
          fontFamily: 'Georgia',
          fill: '#F59E0B',
          textAlign: 'center',
        },
      ],
    },
    ai_prompt: 'Glamorous New Year countdown party invitation with gold and midnight blue',
    is_active: true,
    created_at: '2026-01-14T00:00:00Z',
  },
  {
    id: 'mock-015',
    occasion_slug: 'retirement',
    title: 'Joyful Retirement Farewell',
    style_tags: ['elegant', 'warm', 'classic'],
    colour_palette: ['#F59E0B', '#FEF3C7', '#FFFBEB', '#92400E'],
    orientation: 'portrait',
    price_inr: 29,
    preview_url: null,
    hd_template_url: null,
    fabric_json: {
      version: '5.5.2',
      background: '#FFFBEB',
      objects: [
        {
          type: 'rect',
          version: '5.5.2',
          originX: 'left',
          originY: 'top',
          left: 0,
          top: 0,
          width: 800,
          height: 1000,
          fill: '#FFFBEB',
          stroke: '#FCD34D',
          strokeWidth: 8,
          rx: 0,
          ry: 0,
          selectable: false,
        },
        {
          type: 'textbox',
          version: '5.5.2',
          originX: 'center',
          originY: 'top',
          left: 400,
          top: 90,
          width: 700,
          text: '🏖️ Retirement Party!',
          fontSize: 48,
          fontFamily: 'Playfair Display',
          fontWeight: 'bold',
          fill: '#92400E',
          textAlign: 'center',
        },
        {
          type: 'textbox',
          version: '5.5.2',
          originX: 'center',
          originY: 'top',
          left: 400,
          top: 210,
          width: 680,
          text: 'Celebrating 35 years of dedicated service\nof Mr. Ramesh Nair\nas he begins a new chapter',
          fontSize: 24,
          fontFamily: 'Georgia',
          fill: '#B45309',
          textAlign: 'center',
        },
        {
          type: 'textbox',
          version: '5.5.2',
          originX: 'center',
          originY: 'top',
          left: 400,
          top: 530,
          width: 640,
          text: '📅 Friday, 31st January 2026\n⏰ 6:30 PM\n📍 ITC Hotel Grand, Kochi\nKerala',
          fontSize: 24,
          fontFamily: 'Georgia',
          fill: '#92400E',
          textAlign: 'center',
        },
        {
          type: 'textbox',
          version: '5.5.2',
          originX: 'center',
          originY: 'top',
          left: 400,
          top: 870,
          width: 580,
          text: 'Felicitation | Dinner | Musical Evening\nAll colleagues and well-wishers welcome\nRSVP: 94470 88756',
          fontSize: 18,
          fontFamily: 'Georgia',
          fill: '#B45309',
          textAlign: 'center',
        },
      ],
    },
    ai_prompt: 'Warm and cheerful retirement party invitation with golden amber tones',
    is_active: true,
    created_at: '2026-01-15T00:00:00Z',
  },
  {
    id: 'mock-016',
    occasion_slug: 'birthday-milestone',
    title: 'Golden 50th Milestone',
    style_tags: ['gold', 'elegant', 'festive'],
    colour_palette: ['#7C3AED', '#EDE9FE', '#F5F3FF', '#4C1D95'],
    orientation: 'portrait',
    price_inr: 49,
    preview_url: null,
    hd_template_url: null,
    fabric_json: {
      version: '5.5.2',
      background: '#F5F3FF',
      objects: [
        {
          type: 'rect',
          version: '5.5.2',
          originX: 'left',
          originY: 'top',
          left: 0,
          top: 0,
          width: 800,
          height: 1000,
          fill: '#F5F3FF',
          stroke: '#C4B5FD',
          strokeWidth: 8,
          rx: 0,
          ry: 0,
          selectable: false,
        },
        {
          type: 'textbox',
          version: '5.5.2',
          originX: 'center',
          originY: 'top',
          left: 400,
          top: 90,
          width: 700,
          text: '🥳 Turning 50!',
          fontSize: 56,
          fontFamily: 'Playfair Display',
          fontWeight: 'bold',
          fill: '#4C1D95',
          textAlign: 'center',
        },
        {
          type: 'textbox',
          version: '5.5.2',
          originX: 'center',
          originY: 'top',
          left: 400,
          top: 210,
          width: 680,
          text: 'Half a century of living life to the fullest!\nJoin us in celebrating\nSunita\'s Golden Jubilee Birthday',
          fontSize: 24,
          fontFamily: 'Georgia',
          fill: '#6D28D9',
          textAlign: 'center',
        },
        {
          type: 'textbox',
          version: '5.5.2',
          originX: 'center',
          originY: 'top',
          left: 400,
          top: 530,
          width: 640,
          text: '📅 Sunday, 1st March 2026\n⏰ 6:00 PM\n📍 Radisson Blu\nAmritsar, Punjab',
          fontSize: 24,
          fontFamily: 'Georgia',
          fill: '#4C1D95',
          textAlign: 'center',
        },
        {
          type: 'textbox',
          version: '5.5.2',
          originX: 'center',
          originY: 'top',
          left: 400,
          top: 870,
          width: 580,
          text: 'Dinner | Dance | Nostalgia Evening\nFormal Attire Please\nRSVP: 98551 23457',
          fontSize: 18,
          fontFamily: 'Georgia',
          fill: '#6D28D9',
          textAlign: 'center',
        },
      ],
    },
    ai_prompt: 'Elegant 50th birthday milestone invitation with purple and gold accents',
    is_active: true,
    created_at: '2026-01-16T00:00:00Z',
  },
  {
    id: 'mock-017',
    occasion_slug: 'cocktail-party',
    title: 'Rooftop Cocktail Evening',
    style_tags: ['modern', 'sophisticated', 'minimal'],
    colour_palette: ['#4F46E5', '#E0E7FF', '#F8F8FF', '#312E81'],
    orientation: 'landscape',
    price_inr: 49,
    preview_url: null,
    hd_template_url: null,
    fabric_json: {
      version: '5.5.2',
      background: '#0F0A1E',
      objects: [
        {
          type: 'rect',
          version: '5.5.2',
          originX: 'left',
          originY: 'top',
          left: 0,
          top: 0,
          width: 1200,
          height: 800,
          fill: '#0F0A1E',
          stroke: '#6366F1',
          strokeWidth: 6,
          rx: 0,
          ry: 0,
          selectable: false,
        },
        {
          type: 'textbox',
          version: '5.5.2',
          originX: 'center',
          originY: 'top',
          left: 600,
          top: 80,
          width: 1000,
          text: '🍹 Cocktail Evening',
          fontSize: 56,
          fontFamily: 'Playfair Display',
          fontWeight: 'bold',
          fill: '#A5B4FC',
          textAlign: 'center',
        },
        {
          type: 'textbox',
          version: '5.5.2',
          originX: 'center',
          originY: 'top',
          left: 600,
          top: 200,
          width: 900,
          text: 'You are cordially invited to\nan exclusive rooftop cocktail gathering',
          fontSize: 28,
          fontFamily: 'Georgia',
          fill: '#818CF8',
          textAlign: 'center',
        },
        {
          type: 'textbox',
          version: '5.5.2',
          originX: 'center',
          originY: 'top',
          left: 600,
          top: 440,
          width: 800,
          text: '📅 Saturday, 21st March 2026\n⏰ 8:00 PM\n📍 Sky Lounge, DLF Cyberhub, Gurgaon',
          fontSize: 26,
          fontFamily: 'Georgia',
          fill: '#C7D2FE',
          textAlign: 'center',
        },
        {
          type: 'textbox',
          version: '5.5.2',
          originX: 'center',
          originY: 'top',
          left: 600,
          top: 700,
          width: 700,
          text: 'Craft Cocktails | Canapes | Jazz Music\nDress: Smart Casual\nRSVP: Aryan 99110 22334',
          fontSize: 20,
          fontFamily: 'Georgia',
          fill: '#6366F1',
          textAlign: 'center',
        },
      ],
    },
    ai_prompt: 'Sophisticated dark-themed cocktail party invitation with indigo accents',
    is_active: true,
    created_at: '2026-01-17T00:00:00Z',
  },
  {
    id: 'mock-018',
    occasion_slug: 'farewell',
    title: 'Heartfelt Farewell Gathering',
    style_tags: ['warm', 'emotional', 'elegant'],
    colour_palette: ['#7C3AED', '#DDD6FE', '#F5F3FF', '#4C1D95'],
    orientation: 'portrait',
    price_inr: 0,
    preview_url: null,
    hd_template_url: null,
    fabric_json: {
      version: '5.5.2',
      background: '#F5F3FF',
      objects: [
        {
          type: 'rect',
          version: '5.5.2',
          originX: 'left',
          originY: 'top',
          left: 0,
          top: 0,
          width: 800,
          height: 1000,
          fill: '#F5F3FF',
          stroke: '#DDD6FE',
          strokeWidth: 6,
          rx: 0,
          ry: 0,
          selectable: false,
        },
        {
          type: 'textbox',
          version: '5.5.2',
          originX: 'center',
          originY: 'top',
          left: 400,
          top: 90,
          width: 700,
          text: '👋 Farewell Party',
          fontSize: 50,
          fontFamily: 'Playfair Display',
          fontWeight: 'bold',
          fill: '#4C1D95',
          textAlign: 'center',
        },
        {
          type: 'textbox',
          version: '5.5.2',
          originX: 'center',
          originY: 'top',
          left: 400,
          top: 210,
          width: 680,
          text: 'Bidding a fond farewell to\nour beloved colleague Deepak Joshi\nas he embarks on a new journey',
          fontSize: 24,
          fontFamily: 'Georgia',
          fill: '#6D28D9',
          textAlign: 'center',
        },
        {
          type: 'textbox',
          version: '5.5.2',
          originX: 'center',
          originY: 'top',
          left: 400,
          top: 530,
          width: 640,
          text: '📅 Friday, 28th March 2026\n⏰ 7:00 PM\n📍 Office Terrace, Prestige Tech Park\nBengaluru',
          fontSize: 24,
          fontFamily: 'Georgia',
          fill: '#4C1D95',
          textAlign: 'center',
        },
        {
          type: 'textbox',
          version: '5.5.2',
          originX: 'center',
          originY: 'top',
          left: 400,
          top: 870,
          width: 580,
          text: 'Dinner | Memories | Gifts\nAll team members welcome\nRSVP: Priya HR — 96000 77788',
          fontSize: 18,
          fontFamily: 'Georgia',
          fill: '#6D28D9',
          textAlign: 'center',
        },
      ],
    },
    ai_prompt: 'Warm farewell party invitation with purple lavender tones',
    is_active: true,
    created_at: '2026-01-18T00:00:00Z',
  },
  {
    id: 'mock-019',
    occasion_slug: 'pool-party',
    title: 'Summer Splash Pool Party',
    style_tags: ['fun', 'colorful', 'casual'],
    colour_palette: ['#0EA5E9', '#BAE6FD', '#F0F9FF', '#075985'],
    orientation: 'landscape',
    price_inr: 29,
    preview_url: null,
    hd_template_url: null,
    fabric_json: {
      version: '5.5.2',
      background: '#F0F9FF',
      objects: [
        {
          type: 'rect',
          version: '5.5.2',
          originX: 'left',
          originY: 'top',
          left: 0,
          top: 0,
          width: 1200,
          height: 800,
          fill: '#F0F9FF',
          stroke: '#38BDF8',
          strokeWidth: 10,
          rx: 0,
          ry: 0,
          selectable: false,
        },
        {
          type: 'textbox',
          version: '5.5.2',
          originX: 'center',
          originY: 'top',
          left: 600,
          top: 80,
          width: 1000,
          text: '🏊 Pool Party! 🌞',
          fontSize: 60,
          fontFamily: 'Arial Rounded MT Bold',
          fontWeight: 'bold',
          fill: '#075985',
          textAlign: 'center',
        },
        {
          type: 'textbox',
          version: '5.5.2',
          originX: 'center',
          originY: 'top',
          left: 600,
          top: 200,
          width: 900,
          text: "Get your swimsuits and sunscreen!\nThe Malhotra Family's Annual Summer Splash!",
          fontSize: 28,
          fontFamily: 'Arial',
          fill: '#0369A1',
          textAlign: 'center',
        },
        {
          type: 'textbox',
          version: '5.5.2',
          originX: 'center',
          originY: 'top',
          left: 600,
          top: 450,
          width: 800,
          text: '📅 Sunday, 26th May 2026\n⏰ 11:00 AM – 6:00 PM\n📍 Sapphire Springs Resort, Lonavala',
          fontSize: 26,
          fontFamily: 'Arial',
          fill: '#075985',
          textAlign: 'center',
        },
        {
          type: 'textbox',
          version: '5.5.2',
          originX: 'center',
          originY: 'top',
          left: 600,
          top: 700,
          width: 700,
          text: 'Pool Games | BBQ | Music | Mocktails\nKids Welcome! Sunscreen provided\nRSVP: 95432 10987',
          fontSize: 20,
          fontFamily: 'Arial',
          fill: '#0284C7',
          textAlign: 'center',
        },
      ],
    },
    ai_prompt: 'Fun and vibrant summer pool party invitation with sky blue and aqua colors',
    is_active: true,
    created_at: '2026-01-19T00:00:00Z',
  },
  {
    id: 'mock-020',
    occasion_slug: 'eid',
    title: 'Eid Mubarak Celebration',
    style_tags: ['traditional', 'festive', 'elegant'],
    colour_palette: ['#059669', '#A7F3D0', '#ECFDF5', '#064E3B'],
    orientation: 'portrait',
    price_inr: 29,
    preview_url: null,
    hd_template_url: null,
    fabric_json: {
      version: '5.5.2',
      background: '#064E3B',
      objects: [
        {
          type: 'rect',
          version: '5.5.2',
          originX: 'left',
          originY: 'top',
          left: 0,
          top: 0,
          width: 800,
          height: 1000,
          fill: '#064E3B',
          stroke: '#6EE7B7',
          strokeWidth: 8,
          rx: 0,
          ry: 0,
          selectable: false,
        },
        {
          type: 'textbox',
          version: '5.5.2',
          originX: 'center',
          originY: 'top',
          left: 400,
          top: 90,
          width: 700,
          text: '🌙 Eid Mubarak! ⭐',
          fontSize: 52,
          fontFamily: 'Playfair Display',
          fontWeight: 'bold',
          fill: '#A7F3D0',
          textAlign: 'center',
        },
        {
          type: 'textbox',
          version: '5.5.2',
          originX: 'center',
          originY: 'top',
          left: 400,
          top: 210,
          width: 680,
          text: 'The Khan Family\nrequests the honour of your presence\nat our Eid celebration',
          fontSize: 26,
          fontFamily: 'Georgia',
          fill: '#6EE7B7',
          textAlign: 'center',
        },
        {
          type: 'textbox',
          version: '5.5.2',
          originX: 'center',
          originY: 'top',
          left: 400,
          top: 530,
          width: 640,
          text: '📅 Sunday, 31st March 2026\n⏰ After Eid prayers, 11:00 AM\n📍 Khan Residence\nLucknow, Uttar Pradesh',
          fontSize: 24,
          fontFamily: 'Georgia',
          fill: '#A7F3D0',
          textAlign: 'center',
        },
        {
          type: 'textbox',
          version: '5.5.2',
          originX: 'center',
          originY: 'top',
          left: 400,
          top: 870,
          width: 580,
          text: 'Biryani | Seviyan | Sheer Khurma\nAll are welcome — Eid Mubarak!\nRSVP: 98720 34567',
          fontSize: 18,
          fontFamily: 'Georgia',
          fill: '#34D399',
          textAlign: 'center',
        },
      ],
    },
    ai_prompt: 'Beautiful Eid celebration invitation with deep green and crescent moon motifs',
    is_active: true,
    created_at: '2026-01-20T00:00:00Z',
  },
]
